### ISSUE TITLE
CSS3 Flexboxes

### ISSUE THREAD

**Issue by SourceR85** [MarioRicalde/SCSS.tmbundle#168]
``` SCSS
div {
  display: flex;
  flex-direction: row;
  >div {
    order: 0;
  }
}
```

**Comment by alexggordon** [comment]
+1. Is there a status on the fix for this? Is this something up for pull-request grabs?

**Comment by PixelT** [comment]
+1
I think there is a pull request for this: https://github.com/MarioRicalde/SCSS.tmbundle/pull/194

**Comment by cvrebert** [comment]
+1

**Comment by RickyRomero** [comment]
+1
