### ISSUE TITLE
Add CSS3 syntax highlighting from Sublime-CSS3 repo

### ISSUE THREAD

**Issue by ghost** [MarioRicalde/SCSS.tmbundle#176]
I hope it's worthwhile combining the two projects. While I enjoy seeing my compiled CSS properly highlighted with https://github.com/i-akhmadullin/Sublime-CSS3, I can't make use of it working with .scss files.

**Comment by eberkund** [comment]
Yea, I've noticed that certain CSS3 rules are not highlighted properly for example "text-rendering"
