### ISSUE TITLE
Compass 1.0 selectors

### ISSUE THREAD

**Issue by Sirk** [MarioRicalde/SCSS.tmbundle#180]
Hi all,

As in the new Compass version we can write (for bem users) : 

```
.element {
    &__child {
        width:10px;
    }
}
```

which outputs : 

```
.element__child {
    width:10px;
}
```

It would be nice to not highlight this sintax as an error (like in the capture above) :

![capture d ecran 2014-09-30 a 11 09 00](https://cloud.githubusercontent.com/assets/1640743/4455637/88bef1e4-4881-11e4-813d-a828e599c592.png)

Thanks !

**Comment by djfarly** [comment]
:+1:

**Comment by ivayloc** [comment]
:+1: 
Hope this will be supported soon

**Comment by bozhidarc** [comment]
:+1:

**Comment by renarsvilnis** [comment]
:+1: But it's not only related to compass  [as sass also supports the parent selector](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#parent-selector)
