### ISSUE TITLE
SCSS Syntax highlighting compound selectors as errors

### ISSUE THREAD

**Issue by sdempsey** [MarioRicalde/SCSS.tmbundle#203]
Brought this issue up with the cobalt2 theme developer: https://github.com/wesbos/cobalt2/issues/96 
He indicated that they could fix the issue but that this was really more of an issue with the syntax highlighting.  This is basically a copy/paste of the first issue but it applies. 

What I like to do (sort of a _BEM like_ approach).  I have a selector `.custom-tooltip`  I like to create selectors for inner elements such as `.custom-tooltip-content` or `.custom-tooltip-legend`

``` scss
.custom-tooltip {

    &-content {
        //.custom-tooltip-content styles
    }

    &-legend {
        //.custom-tooltip-legend styles
    }
}
```

SCSS syntax renders them like so: 
![screen shot 2016-02-09 at 11 52 30 am](https://cloud.githubusercontent.com/assets/5795146/12923425/b4fcc43c-cf23-11e5-94ea-676b24d92b79.png)

I'd prefer the compound selectors were rendered in the same color as the ampersand/selector name.  

If there's anything I can do to help, please let me know.  

Thanks,
Sean

**Comment by jcloutz** [comment]
Related to #192. As much as I love Sublime this is sufficiently annoying that I've starting using Atom :/

**Comment by sdempsey** [comment]
Sure is.  I thought I had sufficiently searched before opening this.  Closing now.
