### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by kaelig** [MarioRicalde/SCSS.tmbundle#204]
No updates have been made in the past year. This is a problem as this bundle the most widely used syntax highlighter for Sass (SCSS) at the moment, and Sass' syntax keeps evolving while the bundle stays silent.

If there are no plans for @MarioRicalde to carry maintaining this repo, how can the community help making this bundle better, or come up with an official fork?

**Comment by MarioRicalde** [comment]
Greetings,

First of all, I'd like to thank you for coming in and leaving a comment about the issue that this repository has. It has been clear to me for quite some time and I have not been able to find someone that can maintain it and take some of my suggestions to get this off the ground.

It's painful for me to watch this project, which I started back in the day when there was no reliable syntax for SCSS, to just wither away. I'm more than willing to give complete contribution access and advice to _anyone_ who is willing to direct this project towards the right path.

Cheers.

**Comment by EnriqueCanals** [comment]
I wholeheartedly agree. When I first took over as maintainer of the project I had every intention of keeping development moving forward, however I have not been able to dedicate the time necessary to keep up with the needs of the project. If anyone is willing to make the effort to take over this project, please contact @MarioRicalde or myself- we'll be more than happy to discuss what's to be expected and provide you access to keep this project moving on the right path.

**Comment by kaelig** [comment]
I think the community can't thank you both enough for what you've done!

I'm really looking forward to seeing somebody competent in that field step up and maintain this project.

Feel free to retweet this appeal for a maintainer: https://twitter.com/kaelig/status/707678551177175040

**Comment by infininight** [comment]
Speaking from the TextMate side of things if anyone is interested in taking over the bundle but is not experienced with TextMate bundles I can provide support in that regard.

This project is unique in that it directly supports many editors which will make it very hard to find one person to manage everything. It may need to be a bit of a collaborative effort with people with knowledge of the various editors.

Atom from a grammar standpoint only varies from a format perspective, though outside of the grammar is is very different. Sublime depending on the grammar format used is the most divergent. The other editors as best I am aware are some variants of the 1.x TextMate feature-set.

**Comment by druellan** [comment]
I can see many forks that are still maintained. @ravasthi 's seems to be the most active, perhaps you can send an invitation to all forkers to contribute?

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.
