### ISSUE TITLE
@media block is not highlighted

### ISSUE THREAD

**Issue by mfuentesg** [MarioRicalde/SCSS.tmbundle#209]
ST3 Build 3083
OSX El Capitan
Theme: lioshi theme
Color Scheme: Tomorrow

![captura de pantalla 2016-06-28 a la s 22 55 26](https://cloud.githubusercontent.com/assets/8986996/16439120/fd684698-3d8b-11e6-912e-51954e55a728.png)

**Comment by speir-wang** [comment]
Is this package still under maintenance? I've been getting this issue for a long time, I am using Twilight color scheme and Material theme. This issue is so annoying.

**Comment by dreamstyle** [comment]
I don't think it's under maintenance. The support for CSS3 is terrible. 

Finally, I switch to another package called Syntax Highlighting for Sass. It supports Sublime Text, Atom, and TextMate.
https://packagecontrol.io/packages/Syntax%20Highlighting%20for%20Sass
